services:
  barlog:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file: .env
    networks:
      - microservices_network

networks:
  microservices_network:
    external: true

